### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlonBru**
added link for quick access into css file to copy / look

### CODE REVIEW

**Comment by marijnh** [comment]
This readme is often going to be read in a different context, for example on npmjs.com, where that link won't work.

**Comment by AlonBru** [comment]
Fair enough, could be an absolute link.
If you think it's useful...

**Comment by marijnh** [comment]
Sure, an absolute link to github works for me.

**Comment by AlonBru** [comment]
👍 changed

**Comment by marijnh** [comment]
Thanks!

**Pull request merged**
